#= require "lib/jquery-1.8.2.js"
#= require "lib/knockout.js"
#= require "lib/purl.js"
#= require "lib/swipe.js"
#= require "lib/ua-parser.js"

#= require "fc/helpers.coffee"
#= require "fc/ajax.coffee"
#= require "fc/auth.coffee"
#= require "fc/cache.coffee"
#= require "fc/chart.coffee"
#= require "fc/mobile.coffee"
#= require "fc/team.coffee"
#= require "fc/tutorial.coffee"
#= require "fc/user.coffee"

#= require "ext/binding-handlers.coffee"
#= require "ext/text-scroller.coffee"

#= require "viewModels/base.coffee"
#= require "viewModels/login.coffee"
#= require "viewModels/createAccount.coffee"
#= require "viewModels/profile.coffee"
#= require "viewModels/leaderboard.coffee"
#= require "viewModels/connect.coffee"

#= require "viewModels/profile-vm/invites.coffee"
#= require "viewModels/profile-vm/chooseWebImage.coffee"
#= require "viewModels/profile-vm/editBio.coffee"
#= require "viewModels/profile-vm/editGameDaySpot.coffee"
#= require "viewModels/profile-vm/editBraggingRights.coffee"
#= require "viewModels/profile-vm/selectTeam.coffee"
#= require "viewModels/profile-vm/other.coffee"

#= require "viewModels/profile-vm/selectTeam-vm/chooseSport.coffee"
#= require "viewModels/profile-vm/selectTeam-vm/chooseLeague.coffee"
#= require "viewModels/profile-vm/selectTeam-vm/chooseTeam.coffee"
#= require "viewModels/profile-vm/selectTeam-vm/search.coffee"

#= require "viewModels/games-vm/attendanceStreak.coffee"
#= require "viewModels/games-vm/gameFace.coffee"
#= require "viewModels/games-vm/guessTheScore.coffee"

#= require "viewModels/leaderboard-vm/users.coffee"
#= require "viewModels/leaderboard-vm/teamList.coffee"
#= require "viewModels/leaderboard-vm/conference.coffee"
#= require "viewModels/leaderboard-vm/league.coffee"
#= require "viewModels/leaderboard-vm/breakdown.coffee"

#= require "pages.coffee"
#= require "site.coffee"
#= require "lib/jquerymobile-1.2.0.js"