#= require "lib/jquery-1.8.2.js"
#= require "lib/knockout.js"
#= require "lib/swipe.js"
#= require "lib/ua-parser.js"
#= require "lib/date.js"
#= require "lib/jquery.tokeninput.js"

#= require "fc/helpers.coffee"
#= require "fc/ajax.coffee"
#= require "fc/auth.coffee"
#= require "fc/chart.coffee"
#= require "fc/share.coffee"
#= require "fc/images.coffee"
#= require "fc/logger.coffee"
#= require "fc/maps.coffee"
#= require "fc/mobile.coffee"
#= require "fc/msg.coffee"
#= require "fc/nav.coffee"
#= require "fc/push.coffee"
#= require "fc/setup.coffee"
#= require "fc/team.coffee"
#= require "fc/tutorial.coffee"
#= require "fc/user.coffee"
#= require "fc/verified.coffee"

#= require "models/gameData.coffee"
#= require "models/nextGame.coffee"
#= require "models/events.coffee"

#= require "ext/binding-handlers.coffee"
#= require "ext/text-scroller.coffee"

#= require "viewModels/base.coffee"
#= require "viewModels/login.coffee"
#= require "viewModels/createAccount.coffee"
#= require "viewModels/linkAccounts.coffee"
#= require "viewModels/profile.coffee"
#= require "viewModels/leaderboard.coffee"
#= require "viewModels/games.coffee"
#= require "viewModels/share.coffee"

#= require "viewModels/profile-vm/invites.coffee"
#= require "viewModels/profile-vm/chooseWebImage.coffee"
#= require "viewModels/profile-vm/editBio.coffee"
#= require "viewModels/profile-vm/editGameDaySpot.coffee"
#= require "viewModels/profile-vm/editBraggingRights.coffee"
#= require "viewModels/profile-vm/selectTeam.coffee"
#= require "viewModels/profile-vm/other.coffee"
#= require "viewModels/profile-vm/shout.coffee"

#= require "viewModels/profile-vm/selectTeam-vm/chooseSport.coffee"
#= require "viewModels/profile-vm/selectTeam-vm/chooseLeague.coffee"
#= require "viewModels/profile-vm/selectTeam-vm/chooseTeam.coffee"
#= require "viewModels/profile-vm/selectTeam-vm/search.coffee"

#= require "viewModels/resetPassword.coffee"
#= require "viewModels/resetPassword-vm/setPassword.coffee"
#= require "viewModels/resetPassword-vm/submitTemporary.coffee"

#= require "viewModels/games-vm/attendanceStreak.coffee"
#= require "viewModels/games-vm/gameFace.coffee"
#= require "viewModels/games-vm/guessTheScore.coffee"

#= require "viewModels/connect-vm/roster.coffee"
#= require "viewModels/connect-vm/huddle.coffee"
#= require "viewModels/connect-vm/huddle-vm/newTopic.coffee"
#= require "viewModels/connect-vm/huddle-vm/newReply.coffee"
#= require "viewModels/connect-vm/huddle-vm/replies.coffee"
#= require "viewModels/connect-vm/huddle-vm/tagTeams.coffee"

#= require "viewModels/games-vm/gameFace-vm/motivateSelect.coffee"

#= require "viewModels/leaderboard-vm/listview.coffee"
#= require "viewModels/leaderboard-vm/league.coffee"
#= require "viewModels/leaderboard-vm/breakdown.coffee"
#= require "viewModels/leaderboard-vm/breakdownOther.coffee"
#= require "viewModels/leaderboard-vm/myRoster.coffee"
#= require "viewModels/leaderboard-vm/overallFans.coffee"

#= require "viewModels/settings-vm/manageProfiles.coffee"
#= require "viewModels/settings-vm/account.coffee"
#= require "viewModels/settings-vm/manageAccounts.coffee"

#= require "viewModels/settings-vm/verified-vm/player.coffee"
#= require "viewModels/settings-vm/verified-vm/coach.coffee"
#= require "viewModels/settings-vm/verified-vm/authority.coffee"

#= require "viewModels/share-vm/sms.coffee"

#= require "pages.coffee"
#= require "site.coffee"
#= require "lib/jquerymobile-1.2.0.js"